# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'UA Servers'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: node
    #- job_name: wingu-server
    openstack_sd_configs:
    - role: instance
      port: 9100
      region: Johannesburg
      identity_endpoint: https://identity.wingu.co.za:5000/v2.0
      username: See wingu-credentials
      password: See wingu-credentials
      project_name: UbuntuNet Alliance
      project_id: 9ebe3641f917455faba004d627bf1c1c
    relabel_configs:
    - source_labels: [__meta_openstack_public_ip]
      regex:  '(.*)'             # This is the default value.
      target_label: __address__
      replacement: '${1}:9100'
    - source_labels: [__meta_openstack_instance_name]
      target_label: instance
    - regex: __meta_openstack_tag_(.*)
      replacement: 'ua_${1}'
      action: labelmap

  - job_name: 'wacren-cloud'
    static_configs:
      - targets: ['registry.eduid.africa:9100']

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    #- job_name: 'ua-server'

    # Override the global default and scrape targets from this job every 5 seconds.
    #scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

#     static_configs:
#          - targets: ['cadvisor:8080']

  - job_name: 'node-exporter_local'
    static_configs:
    - targets: [127.0.0.1:9100]

  - job_name: 'node-exporter_docker'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    #dns_sd_configs:
    #- names:
    #  - 'tasks.node-exporter'
    #  type: 'A'
    #  port: 9100
    
    static_configs:
    - targets: ['node-exporter:9100']
